receivers:
  fluentforward:
    endpoint: 127.0.0.1:8006 
  otlp:
    protocols:
      grpc:
      http:
  signalfx:
    endpoint: 0.0.0.0:9943
  smartagent/signalfx-forwarder:
    type: signalfx-forwarder
    listenAddress: 0.0.0.0:9080
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop
  smartagent/rabbitmq:
    type: collectd/rabbitmq
    host: rabbitmq
    port: 15672
    username: guest
    password: guest
  smartagent/nginx:
    type: collectd/nginx
    host: web
    port: 8080

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: 512
  resource/environment:
    attributes:
    - key: deployment.environment
      action: insert
      value: robot-shop-docker

#SPLUNK_API_URL=https://api.us1.signalfx.com
#SPLUNK_INGEST_URL=https://ingest.us1.signalfx.com
#SPLUNK_TRACE_URL=https://ingest.us1.signalfx.com/v2/trace

exporters:
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: https://ingest.us1.signalfx.com/v2/trace #"${SPLUNK_TRACE_URL}"
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: https://api.us1.signalfx.com #"${SPLUNK_API_URL}"
    ingest_url: https://ingest.us1.signalfx.com #"${SPLUNK_INGEST_URL}"
  splunk_hec:
    token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: https://ingest.us1.signalfx.com/v1/log #"${SPLUNK_HEC_URL}"
    source: "otel"
    sourcetype: "otel"
  logging:

service:
#  telemetry:
#    logs:
#      level: "debug"

  pipelines:
    traces:
      receivers: [otlp, smartagent/signalfx-forwarder]
      processors: [memory_limiter, batch, resource/environment]
      exporters: [sapm, signalfx]
    metrics:
      receivers: [otlp, signalfx, smartagent/signalfx-forwarder, prometheus/internal, smartagent/rabbitmq, smartagent/nginx]
      processors: [memory_limiter, batch, resource/environment]
      exporters: [signalfx]
    logs: 
      receivers: [fluentforward, otlp]
      processors:
      - memory_limiter
      - batch
      - resource/environment
      exporters: [splunk_hec]

