receivers:
  otlp:
    protocols:
      grpc:
      http:
  prometheus/internal:
    config:
      scrape_configs:
      - job_name: 'otel-collector'
        scrape_interval: 10s
        static_configs:
        - targets: ['0.0.0.0:8888']
        metric_relabel_configs:
          - source_labels: [ __name__ ]
            regex: '.*grpc_io.*'
            action: drop

processors:
  batch:
  memory_limiter:
    check_interval: 2s
    limit_mib: 512
  resource/environment:
    attributes:
    - key: deployment.environment
      action: insert
      value: opentelemetry-demo-webstore

exporters:
  sapm:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    endpoint: "${SPLUNK_TRACE_URL}"
  signalfx:
    access_token: "${SPLUNK_ACCESS_TOKEN}"
    api_url: "${SPLUNK_API_URL}"
    ingest_url: "${SPLUNK_INGEST_URL}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource/environment]
      exporters: [sapm, signalfx]
    metrics/internal:
      receivers: [otlp, prometheus/internal]
      processors: [memory_limiter, batch, resource/environment]
      exporters: [signalfx]

